#!/usr/local/bin/bash

SSH_KEY_NAME="mbp-ed"
PYTHON_VIRTUAL_ENV="$HOME/venv/bin/activate"

. ../../../shell/utilities.sh

# MARK: images

base() {
    (cd base && with-echo packer build base.pkr.hcl)
}

internal() {
    (cd internal && with-echo packer build internal.pkr.hcl)
}

vpn() {
    (cd vpn && with-echo dr -e -d vpn)
}

COMMAND="$1" && shift && $COMMAND "$@"
