// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: api/v1/evolver.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvolverServiceNewSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArchiveId   string `protobuf:"bytes,1,opt,name=archive_id,json=archiveId,proto3" json:"archive_id,omitempty"`
	Population  int64  `protobuf:"varint,2,opt,name=population,proto3" json:"population,omitempty"`
	Generations int32  `protobuf:"varint,3,opt,name=generations,proto3" json:"generations,omitempty"`
}

func (x *EvolverServiceNewSessionRequest) Reset() {
	*x = EvolverServiceNewSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_evolver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvolverServiceNewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolverServiceNewSessionRequest) ProtoMessage() {}

func (x *EvolverServiceNewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_evolver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolverServiceNewSessionRequest.ProtoReflect.Descriptor instead.
func (*EvolverServiceNewSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_evolver_proto_rawDescGZIP(), []int{0}
}

func (x *EvolverServiceNewSessionRequest) GetArchiveId() string {
	if x != nil {
		return x.ArchiveId
	}
	return ""
}

func (x *EvolverServiceNewSessionRequest) GetPopulation() int64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *EvolverServiceNewSessionRequest) GetGenerations() int32 {
	if x != nil {
		return x.Generations
	}
	return 0
}

type EvolverServiceNewSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Best    *EvolverServiceNewSessionResponse_Candidate `protobuf:"bytes,1,opt,name=best,proto3" json:"best,omitempty"`
	Fitness int64                                       `protobuf:"varint,2,opt,name=fitness,proto3" json:"fitness,omitempty"`
}

func (x *EvolverServiceNewSessionResponse) Reset() {
	*x = EvolverServiceNewSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_evolver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvolverServiceNewSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolverServiceNewSessionResponse) ProtoMessage() {}

func (x *EvolverServiceNewSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_evolver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolverServiceNewSessionResponse.ProtoReflect.Descriptor instead.
func (*EvolverServiceNewSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_evolver_proto_rawDescGZIP(), []int{1}
}

func (x *EvolverServiceNewSessionResponse) GetBest() *EvolverServiceNewSessionResponse_Candidate {
	if x != nil {
		return x.Best
	}
	return nil
}

func (x *EvolverServiceNewSessionResponse) GetFitness() int64 {
	if x != nil {
		return x.Fitness
	}
	return 0
}

type EvolverServiceNewSessionResponse_Candidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidateId            string `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	FuncDeclSerializedJson []byte `protobuf:"bytes,2,opt,name=func_decl_serialized_json,json=funcDeclSerializedJson,proto3" json:"func_decl_serialized_json,omitempty"`
}

func (x *EvolverServiceNewSessionResponse_Candidate) Reset() {
	*x = EvolverServiceNewSessionResponse_Candidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_evolver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvolverServiceNewSessionResponse_Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolverServiceNewSessionResponse_Candidate) ProtoMessage() {}

func (x *EvolverServiceNewSessionResponse_Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_evolver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolverServiceNewSessionResponse_Candidate.ProtoReflect.Descriptor instead.
func (*EvolverServiceNewSessionResponse_Candidate) Descriptor() ([]byte, []int) {
	return file_api_v1_evolver_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EvolverServiceNewSessionResponse_Candidate) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *EvolverServiceNewSessionResponse_Candidate) GetFuncDeclSerializedJson() []byte {
	if x != nil {
		return x.FuncDeclSerializedJson
	}
	return nil
}

var File_api_v1_evolver_proto protoreflect.FileDescriptor

var file_api_v1_evolver_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x82,
	0x01, 0x0a, 0x1f, 0x45, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x65, 0x77, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0xef, 0x01, 0x0a, 0x20, 0x45, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x65, 0x77, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x04, 0x62, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x65,
	0x77, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x62, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x66, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x1a, 0x69, 0x0a, 0x09, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x19, 0x66, 0x75,
	0x6e, 0x63, 0x5f, 0x64, 0x65, 0x63, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x16, 0x66,
	0x75, 0x6e, 0x63, 0x44, 0x65, 0x63, 0x6c, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x4a, 0x73, 0x6f, 0x6e, 0x32, 0x71, 0x0a, 0x0e, 0x45, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x65, 0x77,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x65, 0x77, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_evolver_proto_rawDescOnce sync.Once
	file_api_v1_evolver_proto_rawDescData = file_api_v1_evolver_proto_rawDesc
)

func file_api_v1_evolver_proto_rawDescGZIP() []byte {
	file_api_v1_evolver_proto_rawDescOnce.Do(func() {
		file_api_v1_evolver_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_evolver_proto_rawDescData)
	})
	return file_api_v1_evolver_proto_rawDescData
}

var file_api_v1_evolver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_evolver_proto_goTypes = []interface{}{
	(*EvolverServiceNewSessionRequest)(nil),            // 0: api.v1.EvolverServiceNewSessionRequest
	(*EvolverServiceNewSessionResponse)(nil),           // 1: api.v1.EvolverServiceNewSessionResponse
	(*EvolverServiceNewSessionResponse_Candidate)(nil), // 2: api.v1.EvolverServiceNewSessionResponse.Candidate
}
var file_api_v1_evolver_proto_depIdxs = []int32{
	2, // 0: api.v1.EvolverServiceNewSessionResponse.best:type_name -> api.v1.EvolverServiceNewSessionResponse.Candidate
	0, // 1: api.v1.EvolverService.NewSession:input_type -> api.v1.EvolverServiceNewSessionRequest
	1, // 2: api.v1.EvolverService.NewSession:output_type -> api.v1.EvolverServiceNewSessionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_evolver_proto_init() }
func file_api_v1_evolver_proto_init() {
	if File_api_v1_evolver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_evolver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvolverServiceNewSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_evolver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvolverServiceNewSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_evolver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvolverServiceNewSessionResponse_Candidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_evolver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_evolver_proto_goTypes,
		DependencyIndexes: file_api_v1_evolver_proto_depIdxs,
		MessageInfos:      file_api_v1_evolver_proto_msgTypes,
	}.Build()
	File_api_v1_evolver_proto = out.File
	file_api_v1_evolver_proto_rawDesc = nil
	file_api_v1_evolver_proto_goTypes = nil
	file_api_v1_evolver_proto_depIdxs = nil
}
