@api = http://127.0.0.1:8087/api/v1.0.0
# @api = http://stage.deepthinker.app:8080/api/v1.0.0
@createdAt = {{$datetime iso8601}}

###

/// pow

GET {{api}}/pow/challenge HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "intensity": "<int>"
}

###

GET {{api}}/pow/token HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "challenge_id": "<uuid>",
    "answer": "<string>"
}

###

/// account

POST {{api}}/account HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "$schema": "",
    "$url": "",
    "title": "",
    "description": "",
    "type": "",
    "properties": {
        "username": {
            "type": "integer",
            "pii": true,
        }
    },
    "username": "<string>",
    "pow_token": "<uuid>",
}

###

PATCH {{api}}/account/settings HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer
X-Anti-CSRF-Token: <uuid>

{
    "notifications": "<bool>",
}

###

/// session

POST {{api}}/session HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "username": "",
    "password": "",
}

###

DELETE {{api}}/session HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

###

/// payment

POST {{api}}/payment/purchase HTTP/1.1
Content-Type: application/json; charset=utf-8
X-CSRF-Token: <uuid>
Authorization: Bearer

{
    "plan_id": "<uuid>"
}

###

/// customs

POST {{api}}/customs/module HTTP/1.1
Content-Type: multipart/form-data; boundary=------------------------ba2f2477bab928da
Authorization: Bearer

--------------------------ba2f2477bab928da
Content-Disposition: form-data; name="md5sum"

238c5aeae653a6b6b4c013ee3bc6b582
--------------------------ba2f2477bab928da
Content-Disposition: form-data; name="file"; filename="file.zip"
Content-Type: application/zip

< ./artifacts/tde.CodeArchive.2033531773.zip
--------------------------ba2f2477bab928da--

###

@archiveId = 34872de1-cdb5-4bf8-a634-8c66c6f84508

GET {{api}}/customs/module HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

{
    "archive_id": "{{archiveId}}"
}

###

GET {{api}}/customs/module/ast HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

{
    "archive_id": "{{archiveId}}"
}

###

/// evolve

POST {{api}}/evolve/session HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

{
    "archive_id": "<uuid>",
    "target": {

    },
    "config": {

    },
    "iterations": 1
}

###

@sessionId = 9598b0d6-90bc-4647-b491-32b7f8ac04a6

GET {{api}}/evolve/session/{{sessionId}} HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "session_id": "<uuid>",
    "state": "running",
    // "snapshot_id": "<uuid>,
}

###

PATCH  {{api}}/evolve/session/{{sessionId}} HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

{
    "iterations": 2
}

###

GET {{api}}/evolve/session/generation HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

{
    "session_id": "<uuid>",
    "generation": "<id>"
}

###

GET {{api}}/evolve/session/hall-of-fame HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

{
    "session_id": "<uuid>"
}

###

POST {{api}}/evolve/session/runner-results HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

{
    "batch_id": "<uuid>",
    "item": [
        {
            "subject_id": "<uuid>",
            "results"
        }
    ]
}

###

/// runner

POST {{api}}/runner/batch HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer

{
    "file_template": "<uuid>",
    "test": {
        "path": "<string>",
        "name": "<string>",
    },
    "subjects": [
        {
            "subject_id": "<uuid>",
            "func_decl": "<ast>",
        }
    ]
}

###