DROP DATABASE IF EXISTS "TDE";
CREATE DATABASE "TDE";

CREATE TABLE "USER" AS (
    "USER_UUID"     UUID    NOT NULL UNIQUE gen_uuid_v4()
);

CREATE TABLE "USER_CREDITS" AS (
    "USER_UUID"     UUID    NOT NULL UNIQUE,
    "REMAINING"     INTEGER NOT NULL
);

CREATE TABLE "CREDIT_PURCHASE" AS (
    "CP_UUID"       UUID    NOT NULL UNIQUE gen_uuid_v4(),
    "USER_ID"       UUID    NOT NULL,
    "AMOUNT"        UUID    NOT NULL
);

CREATE TABLE "TOKENS" AS (
    "TOKEN_UUID"   UUID 
    "USER_UUID"    UUID,
    "NOT_BEFORE"   TIMESTAMP   NOT NULL, 
    "NOT_AFTER"    TIMESTAMP   NOT NULL,
    "CREATED_AT"   TIMESTAMP   NOT NULL DEFAULT(CURRENT_TIMESTAMP),
    "DELETED_AT"   TIMESTAMP,
);