---
common: &common
  service-discovery-config: /home/ufukty/service_discovery.json
  service-discovery-update-period: 30s
  grace-period: 15s
  router_public: :8080
  router_private: :8081

evolver:
  <<: *common

runner:
  <<: *common

customs:
  <<: *common
  grace-period: 30s
  volume-mount: /mnt/volume_fra1

api_gateway:
  <<: *common

captcha:
  <<: *common
