@api = http://104.248.255.145:8080/api/v1.0.0
@customs = http://159.65.117.216:8080
@createdAt = {{$datetime iso8601}}

###

// MARK: pow

GET {{api}}/pow/challenge HTTP/1.1
Content-Type: application/json

{
    "intensity": "<int>"
}

###

GET {{api}}/pow/token HTTP/1.1
Content-Type: application/json

{
    "challenge_id": "<uuid>",
    "answer": "<string>"
}

###

// MARK: account

POST {{api}}/account HTTP/1.1
Content-Type: application/json

{
    "$schema": "",
    "$url": "",
    "title": "",
    "description": "",
    "type": "",
    "properties": {
        "username": {
            "type": "integer",
            "pii": true,
        }
    },
    "username": "<string>",
    "pow_token": "<uuid>",
}

###

PATCH {{api}}/account/settings HTTP/1.1
Content-Type: application/json
Authorization: Bearer
X-Anti-CSRF-Token: <uuid>

{
    "notifications": "<bool>",
}

###

// MARK: session

POST {{api}}/session HTTP/1.1
Content-Type: application/json

{
    "username": "",
    "password": "",
}

###

DELETE {{api}}/session HTTP/1.1
Content-Type: application/json
Authorization: Bearer

###

// MARK: payment

POST {{api}}/payment/purchase HTTP/1.1
Content-Type: application/json
X-CSRF-Token: <uuid>
Authorization: Bearer

{
    "plan_id": "<uuid>"
}

###

// MARK: module

POST {{api}}/customs/module HTTP/1.1
Content-Type: multipart/form-data; boundary=------------------------ba2f2477bab928da
Authorization: Bearer

--------------------------ba2f2477bab928da
Content-Disposition: form-data; name="file"; filename="file.zip"
Content-Type: application/zip

< ./artifacts/tde.CodeArchive.2033531773.zip
--------------------------ba2f2477bab928da--

###

GET {{api}}/module HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
    "archive_id": "",
    "client_time": "{{createdAt}}"
}

###

GET {{api}}/module/ast HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
    "archive_id": "",
    "client_time": "{{createdAt}}"
}

###

// MARK: evolve

POST {{api}}/evolve/session HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
    "archive_id": "<uuid>"
}

###

GET {{api}}/evolve/session/generation HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
    "session_id": "<uuid>",
    "generation": "<id>"
}

###

GET {{api}}/evolve/session/hall-of-fame HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
    "session_id": "<uuid>"
}

###

POST {{api}}/evolve/session/runner-results HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
    "batch_id": "<uuid>",
    "item": [
        {
            "candidate_id": "<uuid>",
            "results"
        }
    ]
}

###

// MARK: runner

POST {{api}}/runner/batch HTTP/1.1
Content-Type: application/json
Authorization: Bearer

{
    "file_template": "<uuid>",
    "test": {
        "path": "<string>",
        "name": "<string>",
    },
    "candidates": [
        {
            "candidate_id": "<uuid>",
            "func_decl": "<ast>",
        }
    ]
}

###