DROP DATABASE IF EXISTS "EVOLVER";

CREATE DATABASE "EVOLVER";

CONNECT "EVOLVER";

CREATE TYPE "EVO_SESSION_STATE" AS ENUM (
    "INITIAL",
    "CREATING_NEXT_GENERATION",
    "UPLOAD",
    "WAITING_FOR_RESULTS",
    "FINALIZED"
);

CREATE TABLE "EVO_SESSION" (
    "EVO_SESSION_UUID" UUID NOT NULL UNIQUE gen_uuid_v4(),
    "UPLOAD_ID" UUID NOT NULL,
    "STATE" "EVO_SESSION_STATE" DEFAULT "INITIAL"
);

CREATE TABLE "BATCH" (
    "BATCH_ID" UUID NOT NULL UNIQUE gen_uuid_v4(),
    "SESSION_ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP CURRENT_TIMESTAMP
);