---
- hosts: all
  name: Configure all servers
  serial: 100%
  vars:
    workspace_dir: "{{ playbook_dir }}/../../.."

  tasks:
    - name: Restart journald
      systemd:
        name: systemd-journald
        state: restarted
      become: true

    - name: service_discovery.json
      ansible.builtin.copy:
        src: "../artifacts/deployment/service_discovery.json"
        dest: "~/service_discovery.json"
        mode: "0600"

    - name: config.yml
      ansible.builtin.copy:
        src: "files/home/2iuFDs13YDedYc3N/config.yml"
        dest: "/home/2iuFDs13YDedYc3N/config.yml"
        mode: "0600"

    - name: Put the binary and set systemd item
      include_role:
        name: put_and_set
      vars:
        program_name: "{{ hostvars[inventory_hostname].app_slug }}"
      tags: redeploy

- hosts: customs
  name: mount disk
  roles:
    - role: mount_volume
      become: true
