#!/usr/local/bin/bash

cd "$WORKSPACE/platform/stage"

up() {
    FOLDER="$1" && shift # application, vpn etc.
    test -z "$FOLDER" && error "FOLDER is required." && exit 1
    (cd "provisioning/$FOLDER" && with-echo terraform apply "$@" --var-file=../vars.tfvars)
}

down() {
    FOLDER="$1" && shift # application, vpn etc.
    test -z "$FOLDER" && error "FOLDER is required." && exit 1
    (cd "provisioning/$FOLDER" && with-echo terraform destroy "$@" --var-file=../vars.tfvars)
}

re() {
    down "$@" && up "$@"
}

deploy() {
    (cd "deployment" && with-echo ansible-playbook --forks="20" playbook.yml)
}

redeploy() {
    PROGRAM_NAME="$1" && shift
    test -z "$PROGRAM_NAME" && error "PROGRAM_NAME is required." && exit 1
    (cd "deployment" && with-echo ansible-playbook --forks="20" --limit="$PROGRAM_NAME" --tags="redeploy" playbook.yml)
}

all() {
    with-echo up
    with-echo deploy
}

vpn-totp() {
    test -n "$(find artifacts/vpn -name '*totp*')" && (
        cd artifacts/vpn &&
            find . -name '*totp*' | xargs -n 1 cat | qr &&
            find . -name '*totp*' -delete
    )
}

vpn-connect() {
    REGION_SLUG="$1" && shift
    test -z "$REGION_SLUG" && error "REGION_SLUG is required." && exit 1

    sudo -v
    sudo openvpn "$WORKSPACE/platform/stage/artifacts/vpn/dth-do-$REGION_SLUG-provisioner.ovpn"
    # sleep 1 && sudo killall mDNSResponder{,Helper}
    sudo -k
}

COMMAND="$1" && shift && $COMMAND "$@"
