#!/usr/local/bin/bash

. "$WORKSPACE/shell/utilities.sh"
cd "$WORKSPACE/platform/stage"

up() {
    (cd 1-provisioning && with-echo terraform apply)
}

down() {
    (cd 1-provisioning && with-echo terraform destroy)
}

deploy() {
    (cd 2-deployment && with-echo ansible-playbook --forks 20 playbook.yml)
}

redeploy() {
    PROGRAM_NAME="$1" && shift
    (cd 2-deployment && with-echo ansible-playbook --forks="20" --limit="$PROGRAM_NAME" --tags="redeploy" playbook.yml)
}

all() {
    with-echo stage-up
    with-echo stage-deploy
}

COMMAND="$1" && shift && $COMMAND "$@"
