- name: Mount volumes
  shell:
    cmd: |
      mkdir -p /mnt/attached-a
      mkdir -p /mnt/attached-b
      chown {{ app_user }}:{{ app_user }} -R /mnt/attached-a
      chown {{ app_user }}:{{ app_user }} -R /mnt/attached-b
      sed --in-place '/\/mnt\/attached/d' /etc/fstab # remove previous
      echo "$(ls /dev/disk/by-id/scsi-*-a) /mnt/attached-a ext4 defaults,nofail,discard,noatime 0 2" >> /etc/fstab
      echo "$(ls /dev/disk/by-id/scsi-*-b) /mnt/attached-b ext4 defaults,nofail,discard,noatime 0 2" >> /etc/fstab
      mount -a
  args:
    executable: /bin/bash
