// Code generated by "stringer -type=Method"; DO NOT EDIT.

package paths

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GET-0]
	_ = x[POST-1]
	_ = x[PATCH-2]
	_ = x[DELETE-3]
	_ = x[PUT-4]
}

const _Method_name = "GETPOSTPATCHDELETEPUT"

var _Method_index = [...]uint8{0, 3, 7, 12, 18, 21}

func (i Method) String() string {
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
