
DROP DATABASE "EVOLVER";
CREATE DATABASE "EVOLVER";

\connect "EVOLVER";

CREATE TABLE "SESSION" (
    "SESSION_ID"    UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    "ARCHIVE_ID"    UUID NOT NULL,
    "COUNTER"       INTEGER,
    "CONFIG"        JSON,
    "TARGET"        JSON,
    "CREATED_AT"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
