---
- name: "get path to latest binary for {{ program_name }}"
  local_action:
    module: ansible.builtin.shell
    chdir: "{{ workspace_dir }}"
    cmd: "bash commands path-last-build {{ program_name }} linux"
  register: program_name_command
  tags: redeploy

- name: Check if required binary are present
  local_action:
    module: ansible.builtin.assert
    that:
      - "'No such file or directory' not in program_name_command.stderr"
    fail_msg: "Deployment has been aborted. 1 or more binaries are absent."
    quiet: true
  tags: redeploy

- name: Copy binaries
  ansible.builtin.copy:
    src: "{{ workspace_dir }}/{{ program_name_command.stdout }}"
    dest: "/home/2iuFDs13YDedYc3N/{{ program_name }}"
    mode: "0700"
    owner: 2iuFDs13YDedYc3N
    group: 2iuFDs13YDedYc3N
  tags: redeploy

- name: sudo block
  become: true
  block:
    - name: copy systemd file
      ansible.builtin.copy:
        src: "files/etc/systemd/system/{{ program_name }}.service"
        mode: "0700"
        dest: "/etc/systemd/system/{{ program_name }}.service"

    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: enable app-server service
      ansible.builtin.systemd:
        name: "{{ program_name }}"
        state: restarted
  tags: redeploy
