---
router-parameters: &router-parameters
  request-timeout: 200ms
  write-timeout: 15s
  read-timeout: 15s
  idle-timeout: 60s
  grace-period: 15s

common: &common
  <<: *router-parameters
  service-discovery-config: /home/tde_app/service_discovery.json
  service-discovery-update-period: 30s
  router-public: 8080
  router-private: 8081

evolver:
  <<: *common

runner:
  <<: *common

customs:
  <<: *common
  grace-period: 30s
  request-timeout: 20s
  volume-mount: /mnt/attached-a # TODO: add backup disk support

api_gateway:
  <<: *common
  request-timeout: 20s # FIXME: Separate file server and API gateway

captcha:
  <<: *common
