// Code generated by "stringer -type constraint"; DO NOT EDIT.

package traverse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[file-0]
	_ = x[controlFlowCondition-1]
	_ = x[controlFlowInit-2]
	_ = x[typeDefinition-3]
	_ = x[funcTypeDefinition-4]
}

const _constraint_name = "filecontrolFlowConditioncontrolFlowInittypeDefinitionfuncTypeDefinition"

var _constraint_index = [...]uint8{0, 4, 24, 39, 53, 71}

func (i constraint) String() string {
	if i < 0 || i >= constraint(len(_constraint_index)-1) {
		return "constraint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _constraint_name[_constraint_index[i]:_constraint_index[i+1]]
}
