#!/usr/bin/env bash -i

PS4="\033[36m$(realpath --relative-to="$(dirname "$WORKSPACE")" "$(pwd -P)")\033[32m/\$(basename \"\${BASH_SOURCE}\"):\${LINENO}\033[0m\033[33m\${FUNCNAME[0]:+/\${FUNCNAME[0]}():}\033[0m "
set -o xtrace

# MARK: Run

run() {
    PROGRAM_NAME="$1" && shift
    (
        cd "$WORKSPACE/application"
        go run "tde/cmd/$PROGRAM_NAME" --config="$WORKSPACE/platform/local/config.yml" "$@"
    )
}

# run-last-build() {
#     PROGRAM_NAME="$1" && shift
#     PROGRAM_LAST_BUILD="$(last-build $PROGRAM_NAME)"
#     "./application/build/$PROGRAM_LAST_BUILD/darwin/$PROGRAM_NAME" --config="platform/local/config.yml" "$@"
# }

# build-and-run() {
#     PROGRAM_NAME="$1" && shift
#     build "$PROGRAM_NAME"
#     run-last-build "$PROGRAM_NAME" "$@"
# }

SUBCOMMAND="$1" && shift && "$SUBCOMMAND" "$@"
