DROP DATABASE IF EXISTS "EVOLUTION";
CREATE DATABASE "EVOLUTION";
CONNECT "EVOLUTION";

CREATE TYPE "EVO_SESSION_STATE" AS ENUM (
    "INITIAL",
    "CREATING_NEXT_GENERATION",
    "UPLOAD",
    "WAITING_FOR_RESULTS",
    "FINALIZED"
);

CREATE TABLE "EVO_SESSION" (
    "EVO_SESSION_UUID"     UUID    NOT NULL UNIQUE gen_uuid_v4(),
    "UPLOAD_ID"            UUID    NOT NULL,
    "STATE"                "EVO_SESSION_STATE" DEFAULT "INITIAL"
);