---
- hosts: localhost
  name: preparation
  tasks:
    - name: Compile
      ansible.builtin.shell:
        chdir: ../../../
        cmd: make evolver-server

- hosts: evolution
  name: Configure evolution server
  tasks:
    - name: Copy runner IPs
      ansible.builtin.copy:
        dest: "~/runner_ip_addresses.txt"
        mode: "0600"
        content: |
          {% for host in groups['runners'] %}
          {{ hostvars[host]['ansible_host'] }}
          {% endfor %}

    - name: Copy binaries
      ansible.builtin.copy:
        src: "../../../build/evolver-server"
        dest: "~/evolver-server"
        mode: "0700"
