
DROP DATABASE "CUSTOMS";
CREATE DATABASE "CUSTOMS";

\connect "CUSTOMS";

CREATE TABLE "UPLOAD" (
    "ARCHIVE_ID"    UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    "USER_ID"       UUID NOT NULL,
    "BASED_ON"      UUID,
    "CREATED_AT"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "GENERATION" (
    "GENERATION_ID" UUID NOT NULL,
    "BASED_ON"      UUID
);
