
DROP DATABASE "CUSTOMS";
CREATE DATABASE "CUSTOMS";

\connect "CUSTOMS";

CREATE TABLE "UPLOAD" (
    "ARCHIVE_ID"    UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    "USER_ID"       UUID NOT NULL,
    "CREATED_AT"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "GENERATION" (
    "GENERATION_ID" UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    "ARCHIVE_ID"    UUID NOT NULL,
    "CREATED_AT"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "CANDIDATE" (
    "CANDIDATE_ID"  UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    "GENERATION_ID" UUID NOT NULL,
    "FILE_PATH"     TEXT NOT NULL, -- JSON ENCODED AST
    "CREATED_AT"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
