---
common: &common
  service-discovery-config: 75c31fcc-6dca-5e99-9bad-ea82ad9fe1f6
  service-discovery-update-period: 5s
  grace-period: 1s
  router_public: 8080
  router_private: 8081

evolver:
  <<: *common

runner:
  <<: *common

customs:
  <<: *common
  volume-mount: "NA"

api_gateway:
  <<: *common

captcha:
  <<: *common
