// Code generated by "stringer -type constraint"; DO NOT EDIT.

package traverse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[File-0]
	_ = x[GenDecl-1]
	_ = x[FuncDecl-2]
	_ = x[FuncTypeDef-3]
	_ = x[StructTypeDef-4]
	_ = x[ControlFlowCond-5]
	_ = x[ControlFlowInit-6]
	_ = x[ImportSpec-7]
}

const _constraint_name = "FileGenDeclFuncDeclFuncTypeDefStructTypeDefControlFlowCondControlFlowInitImportSpec"

var _constraint_index = [...]uint8{0, 4, 11, 19, 30, 43, 58, 73, 83}

func (i constraint) String() string {
	if i < 0 || i >= constraint(len(_constraint_index)-1) {
		return "constraint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _constraint_name[_constraint_index[i]:_constraint_index[i+1]]
}
