---
- name: "get path to latest binary for {{ program_name }}"
  local_action:
    module: ansible.builtin.shell
    chdir: "{{ inventory_dir }}/../../"
    cmd: "bash commands last-build {{ program_name }}"
  register: program_name_command

- name: Check if required binary are present
  local_action:
    module: ansible.builtin.assert
    that:
      - "'No such file or directory' not in program_name_command.stderr"
    fail_msg: "Deployment has been aborted. 1 or more binaries are absent."
    quiet: true

- name: Copy binaries
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/../../build/{{ program_name_command.stdout }}/{{ program_name }}-linux-amd64"
    dest: /home/ufukty/customs
    mode: "0700"
    owner: ufukty
    group: ufukty

- name: sudo block
  become: true
  block:
    - name: copy systemd file
      ansible.builtin.copy:
        src: "files/etc/systemd/system/{{ program_name }}.service"
        mode: "0700"
        dest: "/etc/systemd/system/{{ program_name }}.service"

    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: enable app-server service
      ansible.builtin.systemd:
        name: "{{ program_name }}"
        state: restarted
