#!/bin/bash

cd $WORKSPACE/platform/stage/provisioning/vpn

up() {
    terraform apply --var-file=../vars.tfvars
}

destroy() {
    terraform destroy --var-file=../vars.tfvars
}

SUBCOMMAND="$1" && shift && $SUBCOMMAND "$@"
