#!/bin/bash

cd $WORKSPACE/platform/stage/provisioning/vpn

up() {
    terraform apply "$@" --var-file=../vars.tfvars
}

destroy() {
    terraform destroy "$@" --var-file=../vars.tfvars
}

re() {
    destroy "$@" && up "$@"
}

# add_client() {

# }

SUBCOMMAND="$1" && shift && $SUBCOMMAND "$@"
